name: 'Terraform Images'

trigger:
- main

pool:
  vmImage: ubuntu-20.04

jobs:
- job: Create_ACR
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Main Subscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name es-test --location uksouth
        az acr create --resource-group es-test --name esAcRegistry --sku Basic

- job: Terraform_
  dependsOn: Create_ACR
  strategy:
    matrix:
      min_supported_version:
        TERRAFORM_VERSION: '0.14.0'
      mid_supported_version:
        TERRAFORM_VERSION: '0.15.0'
      latest_supported_version:
        TERRAFORM_VERSION: '1.0.0'
    maxParallel: "3"
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Main Subscription'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ls -l
        #az acr build --registry esAcRegistry --image $TERRAFORM_VERSION:v1 .
          
     

