name: 'Build Test Images:'

trigger:
- main

pool:
  vmImage: ubuntu-20.04

jobs:
- job: "Terraform_"
  strategy:
    matrix:
      min_supported_version:
        TERRAFORM_VERSION: '0.14.0'
      mid_supported_version:
        TERRAFORM_VERSION: '0.15.0'
      latest_supported_version:
        TERRAFORM_VERSION: '1.0.0'
    maxParallel: "3"