name: "Terraform Images"

trigger:
  - main

pool:
  vmImage: ubuntu-20.04

variables:
  ARM_TENANT_ID: $(TENANT_ID)
  ARM_CLIENT_ID: $(CLIENT_ID)
  ARM_CLIENT_SECRET: $(CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
jobs:
  - job: Terraform_
    strategy:
      matrix:
        min_supported_version:
          TERRAFORM_VERSION: "0.14.0"
          AZURERM_PROVIDER: "2.41.0"
        mid_supported_version:
          TERRAFORM_VERSION: "0.15.0"
          AZURERM_PROVIDER: "2.62.0"
        latest_supported_version:
          TERRAFORM_VERSION: "1.0.0"
          AZURERM_PROVIDER: "2.70.0"
    steps:
      - task: Bash@3
        name: "print_env"
        inputs:
          targetType: "inline"
          script: |
            echo "TenantID is:$ARM_TENANT_ID"
            echo "ClientID is:$ARM_CLIENT_ID"
          workingDirectory: "tests/"

      - task: Bash@3
        name: "docker_build"
        inputs:
          targetType: "inline"
          script: |
            docker build --build-arg TERRAFORM_VERSION=$TERRAFORM_VERSION --build-arg AZURERM_PROVIDER=$AZURERM_PROVIDER -t "$TERRAFORM_VERSION:$AZURERM_PROVIDER" .
          workingDirectory: "tests/"

      - task: Bash@3
        name: "docker_run"
        inputs:
          targetType: "inline"
          script: |
            docker run -e ARM_TENANT_ID=$ARM_TENANT_ID -e ARM_CLIENT_ID=$ARM_CLIENT_ID -e ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET \
            -e ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID "$TERRAFORM_VERSION:$AZURERM_PROVIDER"
          workingDirectory: "tests/"
