name: 'Terraform Images Build'

trigger:
- main

pool:
  vmImage: ubuntu-20.04

jobs:
- job: "Create_ACR"
  steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          az group create --name es-test --location uksouth
          az acr create --resource-group es-test \
          --name esAcRegistry --sku Basic

- job: "Terraform_"
  strategy:
    matrix:
      min_supported_version:
        TERRAFORM_VERSION: '0.14.0'
      mid_supported_version:
        TERRAFORM_VERSION: '0.15.0'
      latest_supported_version:
        TERRAFORM_VERSION: '1.0.0'
    maxParallel: "3"
  steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo $TERRAFORM_VERSION
